### ISSUE TITLE
Could the system autorestart mechanism and release_autorun.sh loop conflict with each other?

### ISSUE THREAD

**Issue by lamat1111** [0xOzgur/QuilibriumTools#11]
**Double Restart Mechanism:** 
Both the systemd service file and the release_autorun.sh script are responsible for restarting the process.

**Potential Conflict:**

Simultaneous Restart Attempts: 
If the process crashes, both systemd and the script's internal loop may attempt to restart the process almost simultaneously. 

This can create a race condition where:
Systemd restarts the entire service (including the script).
The script's loop detects the process crash and attempts to restart it as well.
This redundancy can lead to inefficient behavior, where the script might start a process just as systemd is restarting the entire service, causing unnecessary restarts and potential instability.

**Git Update Handling:** 
If the script is performing a Git update (e.g., git pull) and systemd restarts the service during this operation, it might interrupt the update process, leading to incomplete updates or corrupted states.

**Comment by 0xOzgur** [comment]
I see possible issue.
What I experienced from many nodes, I haven't seen a such a proble in reality.

Lets wait and see if this is gonna be real issue or not.

**Comment by lamat1111** [comment]
I have done more testing and I think the release_autorun gives issues when trying to stop the service.
Have you ever tried to stop the service, but it doesn't stop, and it takes 2 or 3 times before it's correctly stopped?
This often happens to me. I am not sure if the release_autorun has something to do with this, but maybe yes... never had this issue when running from binary.

**Comment by 0xOzgur** [comment]
No actually, when I stop service, it stops, don't have a problem. Sometimes at heavy loads it take some time to stop, there are some delay but not important.
