### ISSUE TITLE
release_autorun.sh not restarting the node if it crashes

### ISSUE THREAD

**Issue by lamat1111** [0xOzgur/QuilibriumTools#20]
Ref: https://t.me/quilibrium/71642

In release_autorun.sh

```
while true; do
    if ! is_process_running; then
        echo "process crashed or stopped. restarting..."
        start_process
    fi

    fetch

    if $new_release; then
        kill_process

        start_process
    fi

    sleep 43200
done
```

Since the sleep 43200 is outside of the if statements, the script will wait for 12 hours before checking if the process is running again or fetching new releases. This means it will only check the process status and fetch new releases once every 12 hours, which is not ideal for promptly restarting a crashed process.

**Comment by lamat1111** [comment]
@Dekojo proposed solution
https://pastebin.com/d58svC6E

**Comment by nero08** [comment]
created pull request here:

https://github.com/QuilibriumNetwork/ceremonyclient/pull/249
